name: Lint

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: "Install"
        run: |
          yarn

      - name: Lint
        run: yarn lint